global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Tiny_GymBook.Models;
global using Tiny_GymBook.Presentation;
global using Tiny_GymBook.Services.Endpoints;
global using Tiny_GymBook.DataContracts;
global using Tiny_GymBook.DataContracts.Serialization;
global using Tiny_GymBook.Services.Caching;
global using Tiny_GymBook.Client;
global using Uno.Extensions.Http.Kiota;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
